version: "3.9"
services:
  postgres:
    image: postgres:15.0-alpine
    environment:
      POSTGRES_DB: "investdb"
      POSTGRES_USER: "clique"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"